### ISSUE TITLE
The Bluetooth doesn't work.

### ISSUE THREAD

**Issue by marchocode** [edwin170/HP-EliteBook-745-g5-OPENCORE#1]
Hi there.
I finished my Hackintosh yesterday. But I found my Bluetooth can't work normally. 
Have you ever met this case?

**Comment by edwin170** [comment]
> Hi there.
> I finished my Hackintosh yesterday. But I found my Bluetooth can't work normally.
> Have you ever met this case?

nop,the Bluetooth works super well, I can use my headphone Bluetooth, maybe you should use some kext that I use for Bluetooth
